import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/layout/header/header';
import Footer from '@/components/layout/footer/footer';
import { ThemeProvider } from '@/components/darkMode/theme-provider';
import { Lexend } from 'next/font/google';

const font = Lexend({
  weight: ['400', '600'],
  display: 'swap',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          <Header />
          <main className='flex flex-col min-h-screen '>
            <div className='flex-1'>{children}</div>
          </main>

          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
